-- Create tables for action bazaar application.

DROP TABLE BIDS IF EXISTS;

DROP TABLE CATEGORIES_ITEMS IF EXISTS;

DROP TABLE ITEMS IF EXISTS;

CREATE TABLE BIDS (
		BID_ID BIGINT NOT NULL PRIMARY KEY,
		BIDDER_ID VARCHAR(255),
		ITEM_ID BIGINT,
		BID_PRICE DOUBLE
	);