-- Drop action bazaar tables.

DROP TABLE BIDS IF EXISTS;

DROP TABLE CATEGORIES_ITEMS IF EXISTS;

DROP TABLE ITEMS IF EXISTS;

DROP TABLE CATEGORIES IF EXISTS;

DROP TABLE ORDERS IF EXISTS;

DROP TABLE USER_PICTURES IF EXISTS;

DROP TABLE USERS IF EXISTS;

DROP TABLE BILLING_DETAILS IF EXISTS;