-- Create tables for action bazaar application.

DROP TABLE BIDDERS IF EXISTS;

CREATE TABLE BIDDERS (
		USER_ID BIGINT IDENTITY NOT NULL PRIMARY KEY,
		USERNAME VARCHAR(255) NOT NULL,
		PASSWORD VARCHAR(255),
		FIRST_NAME VARCHAR(255),
		LAST_NAME VARCHAR(255),
		CREDIT_CARD_TYPE VARCHAR(255),
		ACCOUNT_NUMBER VARCHAR(255),
		EXPIRY_DATE VARCHAR(255)
	);

DROP TABLE BIDS IF EXISTS;

CREATE TABLE BIDS (
		BID_ID BIGINT NOT NULL PRIMARY KEY,
		BIDDER_ID VARCHAR(255),
		ITEM_ID BIGINT,
		BID_PRICE DOUBLE,
		BID_DATE TIMESTAMP
	);